themes:
  - name: "tokyo-night-term-dark"
    colors:
      - "#16161E"
      - "#1A1B26"
      - "#2F3549"
      - "#444B6A"
      - "#787C99"
      - "#787C99"
      - "#CBCCD1"
      - "#D5D6DB"
      - "#F7768E"
      - "#FF9E64"
      - "#E0AF68"
      - "#41A6B5"
      - "#7DCFFF"
      - "#7AA2F7"
      - "#BB9AF7"
      - "#D18616"
  - name: "vice"
    colors:
      - "#181818"
      - "#222222"
      - "#323232"
      - "#3f3f3f"
      - "#666666"
      - "#818181"
      - "#c6c6c6"
      - "#e9e9e9"
      - "#ff29a8"
      - "#85ffe0"
      - "#f0ffaa"
      - "#0badff"
      - "#8265ff"
      - "#00eaff"
      - "#00f6d9"
      - "#ff3d81"
  - name: "vulcan"
    colors:
      - "#041523"
      - "#122339"
      - "#003552"
      - "#7a5759"
      - "#6b6977"
      - "#5b778c"
      - "#333238"
      - "#214d68"
      - "#818591"
      - "#9198a3"
      - "#adb4b9"
      - "#977d7c"
      - "#977d7c"
      - "#977d7c"
      - "#9198a3"
      - "#977d7c"
  - name: "eldritch"
    colors:
      - "#212337"
      - "#323449"
      - "#3b4261"
      - "#7081d0"
      - "#a1abe0"
      - "#ebfafa"
      - "#f0f2f4"
      - "#ffffff"
      - "#f16c75"
      - "#f7c67f"
      - "#f1fc79"
      - "#37f499"
      - "#04d1f9"
      - "#39ddfd"
      - "#a48cf2"
      - "#f265b5"
  - name: "lavandula"
    colors:
      - "#050014"
      - "#230045"
      - "#372c46"
      - "#463c53"
      - "#554d61"
      - "#645d6f"
      - "#736e7d"
      - "#8c91fa"
      - "#7c1525"
      - "#7f6f49"
      - "#8e86df"
      - "#337e6f"
      - "#57767f"
      - "#4f4a7f"
      - "#593f7e"
      - "#3e0a12"
      - "#241d2e"
      - "#120e17"
      - "#df5066"
      - "#e0c286"
      - "#52e0c4"
      - "#9ad3df"
      - "#8e86df"
      - "#a675df"
  - name: "base2-field"
    colors:
      - "#18201e"
      - "#0fbda0"
      - "#3be381"
      - "#85ffb8"
      - "#25d0b4"
      - "#3be381"
      - "#40ddc3"
      - "#8ea4a0"
      - "#5a6d6a"
      - "#55ec94"
      - "#242e2c"
      - "#42524f"
      - "#667a77"
      - "#88f2e0"
      - "#25d46e"
      - "#a8fff1"
  - name: "ayaka"
    colors:
      - "#36283d"
      - "#71ADE9"
      - "#AB8CAE"
      - "#9EA0D3"
      - "#8BB8E9"
      - "#E1B4CE"
      - "#cedaeb"
      - "#9098a4"
      - "#71ADE9"
      - "#AB8CAE"
      - "#E59DB1"
      - "#9EA0D3"
      - "#8BB8E9"
      - "#E1B4CE"
      - "#cedaeb"
      - "#FFFEFE"
  - name: "base2-suburb"
    colors:
      - "#1e202f"
      - "#7586f5"
      - "#fb6fa9"
      - "#ffb3d2"
      - "#8696fd"
      - "#fb6fa9"
      - "#a0acfe"
      - "#878ba6"
      - "#4f5472"
      - "#fe81b5"
      - "#292c3d"
      - "#444864"
      - "#5b6080"
      - "#d2d8fe"
      - "#f764a1"
      - "#ebedff"
  - name: "gooey"
    colors:
      - "#000009"
      - "#BB4F6C"
      - "#72CCAE"
      - "#C65E3D"
      - "#58B6CA"
      - "#6488C4"
      - "#8D84C6"
      - "#858893"
      - "#1F222D"
      - "#EE829F"
      - "#A5FFE1"
      - "#F99170"
      - "#8BE9FD"
      - "#97BBF7"
      - "#C0B7F9"
      - "#FFFFFF"
  - name: "horizon-dark"
    colors:
      - "#16161C"
      - "#E95678"
      - "#29D398"
      - "#FAB795"
      - "#26BBD9"
      - "#EE64AE"
      - "#59E3E3"
      - "#FADAD1"
      - "#232530"
      - "#EC6A88"
      - "#3FDAA4"
      - "#FBC3A7"
      - "#3FC6DE"
      - "#F075B7"
      - "#6BE6E6"
      - "#FDF0ED"
  - name: "tn-blue"
    colors:
      - "#00346E"
      - "#FF9DA4"
      - "#D1F1A9"
      - "#FFEEAD"
      - "#BBDAFF"
      - "#EBBBFF"
      - "#99FFFF"
      - "#FFFFFF"
      - "#7285B7"
      - "#FF9DA4"
      - "#D1F1A9"
      - "#FFEEAD"
      - "#BBDAFF"
      - "#EBBBFF"
      - "#99FFFF"
      - "#FFFFFF"
  - name: "wyran"
    colors:
      - "#333333"
      - "#8C4665"
      - "#287373"
      - "#7C7C99"
      - "#395573"
      - "#5E468C"
      - "#31658C"
      - "#899CA1"
      - "#3D3D3D"
      - "#BF4D80"
      - "#53A6A6"
      - "#9E9ECB"
      - "#477AB3"
      - "#7E62B3"
      - "#6096BF"
      - "#C0C0C0"
  - name: "b2-evening"
    colors:
      - "#2a2734"
      - "#8a75f5"
      - "#ffad5c"
      - "#ffcc99"
      - "#9a86fd"
      - "#ffad5c"
      - "#afa0fe"
      - "#a4a1b5"
      - "#6c6783"
      - "#ffb870"
      - "#363342"
      - "#545167"
      - "#787391"
      - "#d9d2fe"
      - "#ffa142"
      - "#eeebff"
  - name: "eris"
    colors:
      - "#0a0920"
      - "#13133a"
      - "#23255a"
      - "#333773"
      - "#4a5293"
      - "#606bac"
      - "#7986c5"
      - "#9aaae5"
      - "#f768a3"
      - "#f78968"
      - "#f7d668"
      - "#a2faa8"
      - "#a2faf0"
      - "#258fc4"
      - "#c368f7"
      - "#b85600"
  - name: "outrun"
    colors:
      - "#00002A"
      - "#20204A"
      - "#30305A"
      - "#50507A"
      - "#B0B0DA"
      - "#D0D0FA"
      - "#E0E0FF"
      - "#F5F5FF"
      - "#FF4242"
      - "#FC8D28"
      - "#F3E877"
      - "#59F176"
      - "#0EF0F0"
      - "#66B0FF"
      - "#F10596"
      - "#F003EF"
  - name: "rebecca"
    colors:
      - "#292a44"
      - "#663399"
      - "#383a62"
      - "#666699"
      - "#a0a0c5"
      - "#f1eff8"
      - "#ccccff"
      - "#53495d"
      - "#a0a0c5"
      - "#efe4a1"
      - "#ae81ff"
      - "#6dfedf"
      - "#8eaee0"
      - "#2de0a7"
      - "#7aa5ff"
      - "#ff79c6"
  - name: "rose-pine-moon"
    colors:
      - "#232136"
      - "#2a273f"
      - "#393552"
      - "#6e6a86"
      - "#908caa"
      - "#e0def4"
      - "#e0def4"
      - "#56526e"
      - "#eb6f92"
      - "#f6c177"
      - "#ea9a97"
      - "#3e8fb0"
      - "#9ccfd8"
      - "#c4a7e7"
      - "#f6c177"
      - "#56526e"
  - name: "uwunicorn"
    colors:
      - "#241b26"
      - "#2f2a3f"
      - "#46354a"
      - "#6c3cb2"
      - "#7e5f83"
      - "#eed5d9"
      - "#d9c2c6"
      - "#e4ccd0"
      - "#877bb6"
      - "#de5b44"
      - "#a84a73"
      - "#c965bf"
      - "#9c5fce"
      - "#6a9eb5"
      - "#78a38f"
      - "#a3a079"
  - name: "cyb-alt"
    colors:
      - "#fffa6a"
      - "#00bfff"
      - "#df95ff"
      - "#86cbfe"
      - "#ffffff"
      - "#000000"
      - "#ff8aa4"
      - "#21f6bc"
      - "#fff787"
      - "#1bccfd"
      - "#e6aefe"
      - "#99d6fc"
      - "#ffffff"
      - "#332a57"
      - "#e5e5e5"
      - "#c1deff"
  - name: "cyberdyne"
    colors:
      - "#d2a700"
      - "#0071cf"
      - "#ff90fe"
      - "#6bffdd"
      - "#f1f1f1"
      - "#2e2e2e"
      - "#ffc4be"
      - "#d6fcba"
      - "#fffed5"
      - "#c2e3ff"
      - "#ffb2fe"
      - "#e6e7fe"
      - "#ffffff"
      - "#151144"
      - "#00ff92"
      - "#454d96"
  - name: "synth-alpha"
    colors:
      - "#fdf834"
      - "#2186ec"
      - "#f85a21"
      - "#12c3e2"
      - "#ffffff"
      - "#000000"
      - "#f841a0"
      - "#25c141"
      - "#fdf454"
      - "#2f9ded"
      - "#f97137"
      - "#19cde6"
      - "#ffffff"
      - "#000000"
      - "#dad9c7"
      - "#19cde6"
  - name: "terafox"
    colors:
      - "#fda47f"
      - "#5a93aa"
      - "#ad5c7c"
      - "#a1cdd8"
      - "#ebebeb"
      - "#4e5157"
      - "#eb746b"
      - "#8eb2af"
      - "#fdb292"
      - "#73a3b7"
      - "#b97490"
      - "#afd4de"
      - "#eeeeee"
      - "#152528"
      - "#e6eaea"
      - "#293e40"
  - name: "tn-burns"
    colors:
      - "#fda47f"
      - "#5a93aa"
      - "#ad5c7c"
      - "#a1cdd8"
      - "#ebebeb"
      - "#4e5157"
      - "#eb746b"
      - "#8eb2af"
      - "#fdb292"
      - "#73a3b7"
      - "#b97490"
      - "#afd4de"
      - "#eeeeee"
      - "#152528"
      - "#e6eaea"
      - "#293e40"
  - name: "base2-pool"
    colors:
      - "#2a2433"
      - "#aa75f5"
      - "#f87972"
      - "#ffb6b3"
      - "#b886fd"
      - "#f87972"
      - "#c7a0fe"
      - "#9a90a7"
      - "#635775"
      - "#fc8983"
      - "#372f42"
      - "#574b68"
      - "#706383"
      - "#e4d2fe"
      - "#f36f68"
      - "#f3ebff"
  - name: "base2-mall"
    colors:
      - "#1e1e1f"
      - "#a17efc"
      - "#75bfff"
      - "#b3dbff"
      - "#b294ff"
      - "#75bfff"
      - "#c5adff"
      - "#97959d"
      - "#5e5c60"
      - "#8ac8ff"
      - "#2b2b2c"
      - "#515053"
      - "#6a686e"
      - "#e5dbff"
      - "#69b5f7"
      - "#f4f0ff"
  - name: "base2-suburb"
    colors:
      - "#1e202f"
      - "#7586f5"
      - "#fb6fa9"
      - "#ffb3d2"
      - "#8696fd"
      - "#fb6fa9"
      - "#a0acfe"
      - "#878ba6"
      - "#4f5472"
      - "#fe81b5"
      - "#292c3d"
      - "#444864"
      - "#5b6080"
      - "#d2d8fe"
      - "#f764a1"
      - "#ebedff"
  - name: "heetch"
    colors:
      - "#190134"
      - "#392551"
      - "#5A496E"
      - "#7B6D8B"
      - "#9C92A8"
      - "#BDB6C5"
      - "#DEDAE2"
      - "#FEFFFF"
      - "#27D9D5"
      - "#5BA2B6"
      - "#8F6C97"
      - "#C33678"
      - "#F80059"
      - "#BD0152"
      - "#82034C"
      - "#470546"
