#!/bin/env sh
sketchybar --add item ntfy left \
           --set ntfy icon=󰂜 \
                      label=" " \
                      icon.color="$ACCENT_COLOR" \
                      label.color="$TEXT_COLOR" \
                      click_script="sketchybar --set ntfy icon=󰂜"
