#!/usr/bin/env bash
# Generated by pywal16 for SketchyBar & Jankyborders

# UI Roles
export BAR_COLOR=0xd0{background.strip}
export ITEM_BG=0x44{foreground.strip}
export ACCENT_COLOR=0xff{color4.strip}
export ACCENT_FG=0xff{background.strip}
export TEXT_COLOR=0xff{foreground.strip}

# Standard Palette Mappings (Fixes missing $YELLOW, $BLUE, etc.)
export BLACK=0xff{color0.strip}
export RED=0xff{color1.strip}
export GREEN=0xff{color2.strip}
export YELLOW=0xff{color3.strip}
export BLUE=0xff{color4.strip}
export MAGENTA=0xff{color5.strip}
export CYAN=0xff{color6.strip}
export WHITE=0xff{color7.strip}

# Jankyborders Colors
export BORDER_ACTIVE=0xff{color4.strip}     # Focused window border
export BORDER_INACTIVE=0x66{color8.strip}   # Unfocused window border
