#!/usr/bin/env bash

# ｓｋｅｔｃｈｙｂａｒｒｃ


CONFIG_DIR="$HOME/.config/sketchybar"
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"


# ××××××× [ pywal16 ] ×××××××

# requires pywal16 (pipx)

PYWAL_COLORS="$HOME/.cache/wal/colors-sketchybar.sh"
if [ -f "$PYWAL_COLORS" ]; then
  source "$PYWAL_COLORS"
else
  BAR_COLOR=0x40000000
  ITEM_BG=0x44ffffff
  ACCENT_COLOR=0xffffffff
  ACCENT_FG=0xff000000
  TEXT_COLOR=0xffffffff
fi


# ××××××× [ appearance ] ×××××××

# Remove solid background & add vertical offset/margin for a floating look
sketchybar --bar position=top \
                 height=32 \
                 color=0x00000000 \
                 border_color=0x00000000 \
                 y_offset=12 \
                 margin=0


# ××××××× [ defaults ] ×××××××

  island_style=(
  background.color="$BAR_COLOR"
  background.corner_radius=5
  background.height=32
  background.border_width=2
  background.border_color="$ACCENT_COLOR"
  background.drawing=on
  padding_left=10   # Add space between items
  padding_right=10     # Add space between items
  icon.padding_left=10 # Internal space inside the background box
  label.padding_right=10 # Internal space inside the background box
  label.highlight_color="$ACCENT_FG"
  label.color="$TEXT_COLOR"
  icon.font="Hack Nerd Font:Bold:12.0" 
  label.font="Audiowide:Regular:12.0"
  text.width=dynamic
  label.padding_left=10
  label.padding_right=10
  background.shadow.drawing=on
  background.shadow.distance=2
  background.shadow.color="$ITEM_BG"
  background.shadow.angle=20
  text.align=center
)

sketchybar --default "${island_style[@]}"


# ××××××× [ source ] ×××××××

# .✦ ── left side
 
# source "$ITEM_DIR/ntfy_alert"
# set your topic to use ntfy

source "$ITEM_DIR/aerospace.sh"
source "$ITEM_DIR/front_app.sh"

# right side ── .✦

source "$ITEM_DIR/sys_clock"

# rename to match filesystem
source "$ITEM_DIR/battery.sh"

# pkill -f "ntfy_alert" || true
# "$PLUGIN_DIR/ntfy_alert" &

sketchybar --update
